# Generated by Django 4.1.4 on 2022-12-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('o_price', models.FloatField()),
                ('d_price', models.FloatField()),
                ('category', models.CharField(choices=[('Dairy', 'Dairy'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Meat', 'Meat')], max_length=20)),
                ('star', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
