# Generated by Django 4.1.4 on 2022-12-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
