# Generated by Django 4.1.4 on 2022-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_queries_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
