# Generated by Django 4.1.4 on 2023-01-06 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
